---
title: "Resources for Variant Annotation"
teaching: 10 # teaching time in minutes
exercises: 2 # exercise time in minutes
---

- [ ] Fundamentals of variant annotation
- [ ] Explore tools and resources for variant annotation
- [ ] Predicting variant consequneces
- [ ] Annotating allele frequency
- [ ] Annotating predictive variant effect
- [ ] Prioritising variants

## What is variant annotation?
Variant Annotation is the computational process of intersecting raw genomic coordinates (typically from a VCF file) with curated biological databases to assign genetic consequence, functional annotation, and population-level metadata to each identified sequence variation.

A typical setting such as a germline whole exome sequencing from a patient would result in a large number of genetic variants (approximately 30,000). Variant annotation in this case would help provide biological context to these variants and identify key features relacent to the variant that may guide clinical mangement.

<!-- - Use `.md` files for episodes when you want static content
- Use `.Rmd` files for episodes when you need to generate output
- Run `sandpaper::check_lesson()` to identify any issues with your lesson
- Run `sandpaper::build_lesson()` to preview your lesson locally
 -->
<!-- :::::::::::::::::::::::::::::::::::::::::::::::: -->

[r-markdown]: https://rmarkdown.rstudio.com/
